name: mesmer_sparrow
channels:
  - tensorflow
  - conda-forge
dependencies:
  - geopandas=0.12.2
  - leidenalg=0.9.1
  - napari=0.4.18
  - pyqt
  - opencv=4.5.5
  - pip=22.2.2
  - python=3.9
  - rasterio=1.3.2
  - scanpy=1.9.4
  - scipy=1.8.0
  - seaborn=0.11.2
  - fsspec=2023.6.0
  - tensorflow=2.8
  - pip:
      - anndata==0.9.2
      - basicpy==1.0.0
      - jax==0.4.6
      - jaxlib==0.4.6
      - shapely==2.0.1
      - spatial-image==0.3.0
      - multiscale-spatial-image==0.11.2
      - spatialdata==0.0.12
      - squidpy==1.2.0
      - voronoi-diagram-for-polygons==0.1.6
      - xarray==2022.12.0
      - xarray-dataclasses==1.5.0
      - xarray-datatree==0.0.12
      - xarray-schema==0.0.3
      - xarray-spatial==0.3.5
      - pandas==1.4.3
      - deepcell==0.12.9
