[build-system]
requires = ["setuptools>=42.0.0", "wheel"]
build-backend = "setuptools.build_meta"

# pyproject.toml file content
[tool.coverage.run]
omit = [
    "src/napari_sparrow/_tests"/*,
    "experiments/*",
]