delimiter: ","
header: null
column_x: 0
column_y: 1
column_gene: 2
column_midcount: null
debug: False

size_norm: True
min_counts: 10
min_cells: 5
n_comps: 50

min_size: 500
max_size: 100000
pcs: 17
neighbors: 35
spot_size: 70
cluster_resolution: 0.8

polygon_column: ""
polygon_cmap: "magma"
polygon_alpha: 0.5

total_counts_column: "total_counts"
total_counts_cmap: "magma"
total_counts_alpha: 0.5

shape_size_column: "shapeSize"
shape_size_cmap: "magma"
shape_size_alpha: 0.5

leiden_column: "leiden"
leiden_cmap: "magma"
leiden_alpha: 0.5