# path to original working directory the app was executed from
# ${hydra:runtime.cwd}
# Use current cwd path, because interpolation error otherwise at sweep dir https://github.com/facebookresearch/hydra/issues/2247
# Alternative is to use pyrootutils as in https://github.com/ashleve/lightning-hydra-template
work_dir: "/user/gent/436/vsc43666/vscdata"

# path to data directory
data_dir: ${paths.work_dir}/data/

# path to logging directory with all output
log_dir: ${paths.work_dir}/logs/

# path to output directory, created dynamically by hydra
# will be under the log_dir folder
# path generation pattern is specified in `configs/hydra/default.yaml`
# use it to store all files generated during the run, like ckpts and metrics
output_dir: ${hydra:runtime.output_dir}

# default output files
h5ad: ${paths.output_dir}/adata.h5ad
geojson: ${paths.output_dir}/adata.geojson
