defaults:
  - default

# output file names
sdata: ${paths.output_dir}/sdata.zarr

# Plots:
tiling_correction: ${paths.output_dir}/plot_tiling_correction
preprocess: ${paths.output_dir}/plot_preprocess
segmentation: ${paths.output_dir}/plot_segmentation
analyse_genes_left_out: ${paths.output_dir}/plot_analyse_genes_left_out
polygons: ${paths.output_dir}/plot_polygons
preprocess_adata: ${paths.output_dir}/plot_preprocess_adata
total_counts: ${paths.output_dir}/plot_shapes_total_counts
shape_size: ${paths.output_dir}/plot_shapes_size
cluster: ${paths.output_dir}/plot_clustering
leiden: ${paths.output_dir}/plot_shapes_leiden
score_genes: ${paths.output_dir}/plot_score_genes
cluster_cleanliness: ${paths.output_dir}/plot_cluster_cleanliness
nhood: ${paths.output_dir}/plot_nhood_enrichment
